### ISSUE TITLE
Rescued from the Wreckers: The Barry Story

### ISSUE THREAD

**Issue by dsl28** [haggis78/Nexus#10]
As the UK followed suit to modernize with the rest of the world, hundreds of iconic steam locomotives, symbols of industrial might were sidelined, and in another controversial measure to cut costs, the Ministry of Transportation pruned back the national rail network to only include parts with important infrastructure, or lines that were considered profitable. Meanwhile, starting in 1959, the dead, lifeless shells of once proud locomotives made their way from across the nation to Barry, Wales, a seaside town on the southern coast, not far outside Cardiff and Newport. Into the 1970s, nearly 300 locomotives were gathered together on the site, providing quite an interesting contrast to the typical seaside views one might typically expect. Of course, preservationists took this as an oppertunity to save history for future generations, and groups from all walks of life banded together to purchase locomotives for their community, and bring back them to working order. Indeed they did, and today, a total of 213 escaped the cutting torch, with nearly all operating, in museums as display pieces, or used for spare parts on another locomotive. My project's aim is to create a resource that combines photos, data, and other relevant information on the mechanical marvels that once languished here, since existing sites are often little more than text-based lists, or groups of photos. Here's two links and a photo to get your attention.
https://preservedbritishsteamlocomotives.com/saved-from-barry/
http://www.penmorfa.com/Barry/
![barry](https://user-images.githubusercontent.com/70286426/92415162-b3274280-f125-11ea-9f2b-4cc6f183264a.jpg)

**Comment by haggis78** [comment]
That sounds interesting. Can you identify the source material more fully? I note, for example, that the photographs on both websites above are copyrighted.

**Comment by dsl28** [comment]
> That sounds interesting. Can you identify the source material more fully? I note, for example, that the photographs on both websites above are copyrighted.

Of course! I plan on asking the creator about whether I'm able to use their resources. Of course, there are other photo sources through universities/libraries/databases, as well as general fair use policies on a global scale.

**Comment by haggis78** [comment]
@dsl28 OK. You would need to think carefully and creatively about exactly what you would *do* with it, though. How would it differ from the existing websites, other than being newer and flashier?

**Comment by dsl28** [comment]
Ultimately, I'm hoping to use this as a centralized landing point for more information, photos, and links obtaining to each locomotive in the entry, possibly images hosted on Flickr, documents and articles pertaining to them, and/or links to the groups that own, operate, and maintain them.

**Comment by haggis78** [comment]
@dsl28 what would be the base material for your markup itself? What's the content of your XML? I'd just like to be confident that you have appropriate material to work with.

**Comment by dsl28** [comment]
The base material is the listing of https://preservedbritishsteamlocomotives.com/saved-from-barry/ , subdivided into preserved and operational, those still under restoration, parts/spares, scrapyard condition, and then static display.

**Comment by haggis78** [comment]
@dsl28 This is such a cool story, and I'd never heard of it. I've been to Wales but never to the south coast. Crossing it, it reminded me a lot of Pennsylvania: similar rolling hills and the occasional steel mill. No wonder the Welsh came to Pennsylvania, said "Hey, this looks like home", and settled in large numbers.
