### ISSUE TITLE
project proposal

### ISSUE THREAD

**Issue by tlr39** [haggis78/Nexus#12]
I was thinking a good project idea would be on the TV series Game of Thrones. I am still trying to iron out the details, possibly could go one of two ways. One being a project revolved around alternate ending for season 8. If you have watched the series you are familiar with the last season being quite a disappointment. Things that would have taken a whole season to develop were jammed into one episode. My project would be creating a website oriented around major character choices and development that would change the end of the series. Second idea being a project oriented around a "where are they now" feeling. When the series ends, our favorite main characters leave on their own paths. If people were to be interested in this project we would discuss where we think the characters ended up and create a website around their journey from the finale until where they are now.

**Comment by haggis78** [comment]
Can you get access to show scripts? You'll need to start with some kind of text to mark up.

**Comment by haggis78** [comment]
@tlr39 Hooray! Game of Thrones is game on. Your teammates are Joe @gismondijw  and Dylan @slater291 . Amber @amberpeddicord will be your designated instructor team member for this project. This weekend, then, Taylor, launch the new repo, choosing a name (perhaps GoT unless you have some clever one-word reference from the series); invite your teammates and me; and Joe and Dylan, accept the invitation. Someone should write up the short project description for the repo. Everyone should clone the repo to their own computers. If you have links to resources, start an Issue for that.

**Comment by haggis78** [comment]
@tlr39 @gismondijw @slater291 @amberpeddicord Hi all. Your project now has server space set up and a web presence. Over the next two months you'll be creating the content and learning how to post it there yourself. Check out http://got.newtfire.org/ !
