### ISSUE TITLE
George Washington Trail from Pittsburgh to Erie

### ISSUE THREAD

**Issue by JakeCode121** [haggis78/Nexus#13]
This journey was one of the most historic journeys of our not yet a nation's history.  Also, it is an important part of our regional history.  I would like to replicate something similar to the historical markers, providing background information on his journey, possibly on a map.

**Comment by haggis78** [comment]
For the mapping aspect, that would work best in the Spring semester Coding and Data Visualization. For now you might be able to make a simple map, but then you would be able to make a more sophisticated, interactive one. However, a project can run across multiple semesters, so if you think you'd like to take that class -- there would actually be a lot of overlap with this class, so in some ways it wouldn't be as hard -- you could continue your work on this project then, provided that you can persuade a few other students to join you on it. Or if you're committed to this project and it doesn't run this semester, but you still want to do it, you could do it from scratch in the spring semester. So for now, think of it as a collection of marked-up texts. Can you collect historical texts relevant to the journey that you would be able to use?

**Comment by dsl28** [comment]
This is definitely interesting, maybe you could also trace the location of markers along the route, and then include details about the signifigance of each.

**Comment by tlr39** [comment]
Jake, I like this idea. The historical points would be interesting to research and create a website for.

**Comment by ebeshero** [comment]
For this project, it'll help to have some source texts documenting the journey from Pittsburgh to Erie to which you can apply XML markup that *geolocates*, that is, associates places with passages of text. What text resources are available? I wasn't searching for very long, but I did find a digital publication of George Washington's journal from 1754 that you could maybe work with (is that the right time period ?) Take a look: https://digitalcommons.unl.edu/cgi/viewcontent.cgi?article=1033&context=etas 

This is text-searchable, so you could "scrape" it (copy and paste it, or a portion of it, into your own XML file) and work on marking it up. There are lots of other good George Washington resources you could probably find for this project...As a recent transplant from Greensburg to Erie, I find this project idea pretty cool! :-)

**Comment by JakeCode121** [comment]
@ebeshero That is wonderful, thank you.  I'm from North East, Pa, and I'm going up to Erie this weekend.  I was planning on taking the trail and taking pictures.

**Comment by ebeshero** [comment]
@JakeCode121 Northeast is gorgeous! Wine country... :-) And has a funny name for a place in the northwest corner of the state!

**Comment by haggis78** [comment]
@JakeCode121 It's clear now that Washington Trail is a go! Congratulations. Your teammates are @dsl28 and @mld137. All three of you had proposed interesting historical projects, so I'm glad to see you all working together on one. This weekend, then, Jake, launch the new repo, choosing a name (perhaps Washington-Trail); invite your teammates and me; and Dylan and Mollie, accept the invitation. Someone should write up the short project description for the repo. Everyone should clone the repo to their own computers. If you have links to resources, start an Issue for that. However, GitHub isn't optimal for large files, so Jake, this isn't the best place for a photo dump if you get a lot of good pictures this weekend.

**Comment by haggis78** [comment]
@JakeCode121 Also @Bennediction will be your designated go-to on the instructor team for this project. Be sure to invite him to your repo as well.

**Comment by haggis78** [comment]
@JakeCode121 @mld137 @dsl28 @Bennediction Hi all. Your project now has server space set up and a web presence. Over the next two months you'll be creating the content and learning how to post it there yourself. Check out http://washtrail.newtfire.org/
