### ISSUE TITLE
Regex issue 

### ISSUE THREAD

**Issue by JakeCode121** [haggis78/Nexus#14]
Has anyone experienced and issue with using the ^ symbol?  Every time I use this I receive the message no string found, so I'm unable to continue on with the assignment.  Thanks.

**Comment by haggis78** [comment]
@JakeCode121 , are you missing the fact that each line begins with two whitespaces? So it would be looking for a newline, two whitespaces, and THEN the beginning of the text/Roman Numerals.

**Comment by JakeCode121** [comment]
@haggis78 I'm not sure I typed in ^[IXVC]+$. 
In the find section and nothing came up.  However, when I would type in II or III, I had no problems.

**Comment by haggis78** [comment]
Right. You would want:
 '''^\s\s[IXVC]+$'''

**Comment by haggis78** [comment]
@JakeCode121 it won't find the string you entered because there are two whitespaces between the start of the line and the Roman numeral -- unless you followed the instructions that were part of the assignment and removed all those double whitespaces first.

**Comment by JakeCode121** [comment]
I took the the step 

\n{3,}

And Replaced it with \n\n

**Comment by haggis78** [comment]
@JakeCode121 Let's talk about this in class.
