### ISSUE TITLE
Breaking Bad Project

### ISSUE THREAD

**Issue by gismondijw** [haggis78/Nexus#16]
Breaking Bad is one of the best television dramas ever created. The show focuses on character changes, symbolism, and setting. I want to use dialogue and images of important moments and scenes to depict how the show executes on those three focal points.

**Comment by haggis78** [comment]
Have you checked if you have access to scripts online?

**Comment by dsl28** [comment]
If you're able to get access to the scripts of the show, this is genuinely cool, as I'm also a fan of the show.

**Comment by gismondijw** [comment]
https://8flix.com/breaking-bad/scripts/
I found a website with full scripts for each episode but I am not sure if they are 100% accurate

**Comment by JakeCode121** [comment]
I'm interested in the show: big fa.

**Comment by mjo43** [comment]
Vince Gilligan is a mastermind. There's a lot of symbolism, thought, and meaning put into the series. Cool idea

**Comment by haggis78** [comment]
@gismondijw some day I may actually have to watch the show, since I hear so much about it!
