### ISSUE TITLE
Famous Historical Animals

### ISSUE THREAD

**Issue by khope168** [haggis78/Nexus#17]
Okay, so hear me out, this project topic could be fun for anyone and interesting to research. We can make an archive of the coolest/most famous and most important animals throughout history. Animals like presidential pets, the bear Theodore Roosevelt refused to shoot, Wojtek the Polish Army bear, Dolly the Cloned Sheep, etcetera etcetera. Primary documents can include photos, news articles, published research, or any written record available. I want to make a comprehensive list of history's greatest animals that I can refer back to for random knowledge's sake.  

Picture of Wojtek in case you needed any more convincing:
![](https://i.ytimg.com/vi/twr38iHXYVw/maxresdefault.jpg)

**Comment by haggis78** [comment]
@khope168 This was a fun idea. I'd never heard of Wojtek.
