### ISSUE TITLE
The Avatar Project

### ISSUE THREAD

**Issue by jer179** [haggis78/Nexus#18]
Since Avatar: The Last Airbender was recently released onto Netflix, the show has increased in popularity once again among previous fans and new fans who are just watching it for the first time. My idea for the team projects for this semester is creating a website based on this show. I'm not really sure where I want to go with this yet, however I have a few ideas in mind. One could be focusing on each of the main characters throughout the seasons and all of the challenges they must face. Another idea is based on the 3 seasons (Book 1, Book 2, and Book 3) which are each focused on the main character Aang, learning the ability to bend water, earth, and then fire. I think it would be a cool idea to organize each season based on everything Aang had to do before he could master each element. There could definitely be many other great ideas as to what direction this project would go in, those are just a few. I think this would be a fun project to do with other people who have watched this show and enjoyed it as much as I did!

**Comment by haggis78** [comment]
Those seem like good research questions; you could compare the Teen Titans project from last year. That project used show scripts. Do you have access to those?

**Comment by mjo43** [comment]
Great show. I would be interested. There are tons of fan-made sites out there compiling information from the show.

**Comment by tlr39** [comment]
This is a really cool idea!

**Comment by haggis78** [comment]
@jer179 Congratulations! Avatar is running. Your teammates are Michael @mjo43 and Rowyn @khope168 . Also, I'm happy to say that @smdunn921 Shannon, who was a founding member of the Teen Titans Project, is your designated instructor team member for this project. This weekend, then, Jayna, launch the new repo, choosing a name (probably Avatar); invite your teammates plus Shannon and me; and Michael and Rowyn, accept the invitation. Someone should write up the short project description for the repo. Everyone should clone the repo to their own computers. If you have links to resources, start an Issue for that.

**Comment by haggis78** [comment]
@jer179 @mjo43 @khope168 @smdunn921 Hi all. Your project now has server space set up and a web presence. Over the next two months you'll be creating the content and learning how to post it there yourself. Check out http://avatar.newtfire.org/
