### ISSUE TITLE
Issue with Git Bash; Newtfire password

### ISSUE THREAD

**Issue by khope168** [haggis78/Nexus#19]
Hi all, I hope I'm not the only one running into this problem.
Since last night I haven't been able to set up my SSI key to link to the Newtfire page. I read the instructions, replaced the yourusername in the line with my Pitt username as instructed, entered that temporary password, and Git Bash is telling me Permission Denied and to try a new password. I tried putting it in a couple more times and it closes the connection. Can I get some help?

**Comment by haggis78** [comment]
All: I resolved the issue and sent out an announcement on Canvas. I also fixed the tutorial to reflect the change that needed to be made.
