### ISSUE TITLE
Xpath exercise

### ISSUE THREAD

**Issue by tlr39** [haggis78/Nexus#20]
The attached XML document for our xpath exercise is downloading as a word document and not as an XML doc.

**Comment by haggis78** [comment]
@tlr39 Let me look at that...

**Comment by haggis78** [comment]
@tlr39 It's an .xml document at my end. Did you download, save, and open in oXygen?

**Comment by tlr39** [comment]
It says XML but when downloaded, the icon is not the normal xml, then when opened it opens in word and says "XML characters are not supported." and only gives me text. I have oxygen open and tried to open it in there but it won't open.

**Comment by amberpeddicord** [comment]
@tlr39 What does it say when you open it in oXygen?

**Comment by tlr39** [comment]
When I download it it only lets me save it as a word document which says it deleted all xml characters when saved. A message popped up when I hit save. Should I try to open that in oxygen?

**Comment by haggis78** [comment]
Sure. It can't hurt.

**Comment by haggis78** [comment]
If it doesn't work for some reason, I can try emailing it to you as a file attachment.

**Comment by amberpeddicord** [comment]
@tlr39 When I do it, I just download the file and open it directly from oXygen from my downloads.

**Comment by tlr39** [comment]
That is what I do to but when I click to open it, it opens in word.

**Comment by tlr39** [comment]
Let me save it in word and open in oxygen.

**Comment by haggis78** [comment]
Incidentally, Word actually runs XML under the hood, so that may be where your computer is getting confused.

**Comment by tlr39** [comment]
I opened it through the email link. Thank you!

**Comment by haggis78** [comment]
OK. Glad that worked eventually. And thanks @amberpeddicord .
