### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by BraydenT52** [haggis78/Nexus#22]
I made a new repo because I could not figure out how to make my other repo public. I think I just need this repo added as a contributor.

**Comment by amberpeddicord** [comment]
@BraydenT52 Sorry for the reply at midnight! But, you don't add repos as contributors, just people/accounts, so you're fine! Repos are just workspaces that you create within your GitHub account, and you add contributors through usernames, not repo names. That was wordy, but I hope it helped!
