### ISSUE TITLE
Relax schema

### ISSUE THREAD

**Issue by BraydenT52** [haggis78/Nexus#23]
Hi, so I have been fussing with the assignment that is due today. When I pull up the Gettysburg address, I have no idea how to begin. I am currently watching the video again to try and guide me through it but I was wondering if there is any suggestions that can be given to help me better understand how to start a relaxed schema.

**Comment by haggis78** [comment]
Campbell, William H is inviting you to a scheduled Zoom meeting.

Topic: Campbell, William H's Zoom Meeting
Time: Feb 1, 2021 01:15 PM Eastern Time (US and Canada)

Join Zoom Meeting
https://pitt.zoom.us/j/92170711798

Meeting ID: 921 7071 1798
One tap mobile
+12678310333,,92170711798# US (Philadelphia)
8778535247,,92170711798# US Toll-free

Dial by your location
        +1 267 831 0333 US (Philadelphia)
        877 853 5247 US Toll-free
Meeting ID: 921 7071 1798
Find your local number: https://pitt.zoom.us/u/adn2Y1ePzx

Join by SIP
92170711798@zoomcrc.com

Join by H.323
162.255.37.11 (US West)
162.255.36.11 (US East)
115.114.131.7 (India Mumbai)
115.114.115.7 (India Hyderabad)
213.19.144.110 (Amsterdam Netherlands)
213.244.140.110 (Germany)
103.122.166.55 (Australia Sydney)
103.122.167.55 (Australia Melbourne)
149.137.40.110 (Singapore)
64.211.144.160 (Brazil)
69.174.57.160 (Canada Toronto)
65.39.152.160 (Canada Vancouver)
207.226.132.110 (Japan Tokyo)
149.137.24.110 (Japan Osaka)
Meeting ID: 921 7071 1798



William H. Campbell, PhD, LMS, FRHistS
Visiting Assistant Professor of History and Digital Studies; Director, Center for the Digital Text
University of Pittsburgh-Greensburg
Faculty Office Building 204
150 Finoli Drive
Greensburg, PA 15601

https://greensburg-pitt.academia.edu/CampbellW
________________________________
