### ISSUE TITLE
pop_loadbv import error

### ISSUE THREAD

**Issue by ET-eeg** [haggis78/Nexus#3]
Hello friends, I am trying to import Brain Vision EEG data using the poploadbv function using the following lines.

    twd = [472000 1040000];%the sample window to extract data
    sub = '08022018_LN038';
    EEG = pop_loadbv(['C:\Users\Tim9525\Desktop\LN038\'],[sub,'.vhdr'], twd, []);

Matlab returns with the error:

> Unrecognized function or variable 'fgetline'.
> 
> Error in fgetl (line 23)
> 	y = fgetline(fid);
> 
> Error in readbvconf (line 50)
>     raw = [raw; {fgetl(IN)}];
> 
> Error in pop_loadbv (line 83)
> hdr = readbvconf(path, hdrfile);

Do I need to download a toolbox containing the fgetline function? Where can I get it? Or, there is other problem. Thanks,

**Comment by haggis78** [comment]
Sorry, I think you're in the wrong place. Good luck.
