### ISSUE TITLE
GitHub Exercise 1: Comment Your Usernames!

### ISSUE THREAD

**Issue by amberpeddicord** [haggis78/Nexus#4]
For GitHub Exercise 1, you're all creating GitHub accounts and repositories. This is our class's repo, but you all need to be added as collaborators.

To be added as a collaborator on this repository, comment your GitHub usernames below!

**Comment by JakeCode121** [comment]
hello @amberpeddicord I think I'm added, but @JakeCode121 is my handle

**Comment by gismondijw** [comment]
Hi @amberpeddicord my username is @gismondijw

**Comment by tlr39** [comment]
Hi @amberpeddicord my username should be @tlr39

**Comment by jer179** [comment]
Hi @amberpeddicord my username is @jer179

**Comment by haggis78** [comment]
Welcome Jake @JakeCode121 , Joe @gismondijw , Taylor @tlr39 , and Jayna @jer179 .

**Comment by khope168** [comment]
Hi,it's rowyn, my username is keh168

**Comment by mjo43** [comment]
Hi @amberpeddicord Its Michael, my username is @mjo43

**Comment by slater291** [comment]
Hello @amberpeddicord I'm Dylan and my username is @slater291

**Comment by mld137** [comment]
Hi @amberpeddicord , I'm Mollie my username is mld137

**Comment by Tanajah** [comment]
Tanajah

**Comment by dsl28** [comment]
I'm dylan, @dsl28
