### ISSUE TITLE
UX Discussion of Digital Archive projects

### ISSUE THREAD

**Issue by haggis78** [haggis78/Nexus#5]
Choose one of the following digital archives to explore its features. Spend some time investigating until you're reading some marked-up documents on the site (a manuscript page or an historical document or a poem, etc), and think about how markup was used to design this. Then write a post on this thread that addresses:

something interesting the site is inviting us to explore about centuries-old texts, and
the effectiveness of the user experience (“UX”) in discovering, reading, and learning about these texts.
Archives:
* Shelley-Godwin Archive: Frankenstein Notebooks: http://shelleygodwinarchive.org/contents/frankenstein
* Map of Early Modern London: http://mapoflondon.uvic.ca/index.htm
* Emily Dickinson Project (made by Pitt-Greensburg students in 2015-2016): http://dickinson16.newtfire.org/
* any documents in the Greco-Roman section of the Perseus project, and explore the features here: http://www.perseus.tufts.edu/hopper/collection?collection=Perseus:collection:Greco-Roman

**Comment by tlr39** [comment]
On the Frankenstein page, I think a certain type of code was used to generate the tracing of the evolution of Frankenstein. This site invited us to explore the archive. It provides a video guide for beginners which is helpful. The site is also visually appealing and correctly labeled which makes it easy to navigate.

**Comment by JakeCode121** [comment]
I found the Emily Dickinson project very well written.  The hyperlinks and and the drop down menus were professionally done.  It was clean and easy to navigate, not at all overwhelming.

**Comment by gismondijw** [comment]
The Frankenstein page is well organized as all sections are at the top of the page and easily seen. There are many different documents to read and they are easy to find. The Using the Archive tab is great for user experience as it gives a tutorial on how to use the website.

**Comment by jer179** [comment]
The Map of Early Modern London page is minimalist and easy to navigate. The first thing your eyes are drawn to on the home page is the map. The descriptions are concise and easy to understand, and the artwork on the tabs is inviting for the user to explore.

**Comment by khope168** [comment]
Although in Greek, I thought the organization Marcus Aurelius' M. Antonius Imperator Ad Se Ipsum was exquisitely well-thought. The table of contents and search options are well-placed so that you may look at the provided text while you search. However, the page is very cut and dry which is not very appealing, but it works well for what the site is trying to accomplish.

**Comment by mjo43** [comment]
The Emily Dickinson page, created by Pitt Greensburg students, achieves a simple webpage with effective organization between poems. Highlighted terms and colored boxes illustrate important terms within the poems. I appreciate seeing the original texts and the XML text side by side. Sometimes I got lost when choosing the Fascicles and that same drop down menu then displaying the list of poems, but once I had poems selected it was easy to follow. Overall, the website inspired me to look deeper into the poetry by including original scans of the documents.

**Comment by slater291** [comment]
The Frankenstein page is very neatly organized and simple. The About tab is very informative about the Archive as a whole, the Explore tab sorts the works and manuscripts in a way that's easy to navigate, and the Using the Archive tab is a great tutorial on how to navigate through the site, as well as a good introduction for the material that you can expect to find. My only complaint is that the site lacks any unique visual style and looks quite bland.

**Comment by mld137** [comment]
The Emily Dickinson page is useful for not only giving users a place to find Dickinson's work, users can also see differences in original and published work. The site is easy to navigate and well organized. The color coded tags really help to keep the different versions of the poems clear.

**Comment by dsl28** [comment]
I found the map of early modern London to be quite user friendly, even on a mobile device. The quick link to the map itself makes it easy to jump in and explore an amazingly in-depth project without having to search through endless tabs and menus to find what you’re searching for. In fact, it also happens to be quite stylish as well.
