### ISSUE TITLE
Project proposals!

### ISSUE THREAD

**Issue by haggis78** [haggis78/Nexus#9]
When you come to Nexus to make your project proposal, do so by starting a new issue. Then other students will be able to see your proposal and comment on it.

**Comment by haggis78** [comment]
@khope168 @slater291 I'm putting together project teams this evening. I'd like each of you to tell me, **in order of preference,** what project you'd like to work on, from among these three: Game of Thrones, Hamilton, Avatar. If I don't hear from you tonight I'll have to assign you to a team. That's OK, but I'd like to try to give you options.

**Comment by haggis78** [comment]
@khope168 @slater291 actually, scratch that: the two choices are Game of Thrones and Avatar. First one to tell me which one you want gets it!

**Comment by khope168** [comment]
I'd like Avatar!
